# Generated by Django 3.0.5 on 2020-05-29 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default=1, upload_to='image', verbose_name='头像'),
            preserve_default=False,
        ),
    ]
